openapi: 3.0.5
info:
  description: OpenAPI Specification for the API
  title: API for grocery management
  version: 1.0.0
servers:
- description: Local server
  url: http://localhost:4200/api/v1
tags:
- description: Operations related to roles
  name: Role
paths:
  /role/create:
    post:
      operationId: createRole
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
          description: Role created successfully.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request. Invalid input data.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error. Unable to create role.
      summary: Create a new role
      tags:
      - Role
  /role/update:
    put:
      operationId: updateRole
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleUpdateRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
          description: Role updated successfully.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request. Invalid input data.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Role not found. Unable to update role.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error. Unable to update role.
      summary: Update an existing role
      tags:
      - Role
  /role/delete:
    delete:
      operationId: deleteRole
      parameters:
      - description: The unique identifier of the role to be deleted.
        in: query
        name: id
        required: true
        schema:
          example: 123e4567-e89b-12d3-a456-426614174000
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
          description: Role deleted successfully.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request. Invalid input data.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Role not found. Unable to delete role.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error. Unable to delete role.
      summary: Delete a role
      tags:
      - Role
  /role/get:
    post:
      operationId: getAllRoles
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaginationRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralArrayResponse'
          description: Role retrieved successfully.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request. Invalid input data.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Role not found. Unable to retrieve role.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error. Unable to retrieve role.
      summary: Get all roles
      tags:
      - Role
components:
  schemas:
    RoleRequest:
      example:
        name: admin
        description: Administrator role with full access
        status: active
      properties:
        name:
          description: The name of the role.
          example: admin
          type: string
        status:
          enum:
          - active
          - inactive
          - pending
          - cancelled
          - review
          - deleted
          type: string
        description:
          description: A brief description of the role.
          example: Administrator role with full access
          type: string
      required:
      - description
      - name
      type: object
    GeneralResponse:
      description: General response object
      example:
        code: 0
        data:
          createdAt: 2023-10-01T12:00:00Z
          deletedAt: 2023-10-01T12:00:00Z
          updatedBy: admin
          createdBy: admin
          name: admin
          description: Administrator role with full access
          deletedBy: admin
          status: active
          updatedAt: 2023-10-01T12:00:00Z
        message: message
      properties:
        code:
          description: Response code
          type: integer
        message:
          description: Response message
          type: string
        data:
          $ref: '#/components/schemas/BaseRole'
      type: object
    ErrorResponse:
      example:
        code: 400
        details: The role ID is required
        message: Invalid request
        errors:
        - The role ID is required
        - The role name must be at least 3 characters long
      properties:
        code:
          example: 400
          format: int32
          type: integer
        message:
          example: Invalid request
          type: string
        details:
          example: The role ID is required
          type: string
        errors:
          example:
          - The role ID is required
          - The role name must be at least 3 characters long
          items:
            type: string
          type: array
      required:
      - code
      - details
      - message
      type: object
    RoleUpdateRequest:
      example:
        name: admin
        description: Administrator role with full access
        id: 123e4567-e89b-12d3-a456-426614174000
        status: active
      properties:
        id:
          description: The unique identifier of the role to be updated.
          example: 123e4567-e89b-12d3-a456-426614174000
          type: string
        name:
          description: The name of the role.
          example: admin
          type: string
        status:
          enum:
          - active
          - inactive
          - pending
          - cancelled
          - review
          - deleted
          type: string
        description:
          description: A brief description of the role.
          example: Administrator role with full access
          type: string
      required:
      - id
      type: object
    PaginationRequest:
      example:
        limit: 10
        page: 1
        sort: name
        order: asc
      properties:
        page:
          description: The page number for pagination.
          example: 1
          minimum: 0
          type: integer
        limit:
          description: The number of items per page.
          example: 10
          type: integer
        sort:
          description: The field to sort by.
          example: name
          type: string
        order:
          description: The order of sorting (asc or desc).
          enum:
          - asc
          - desc
          example: asc
          type: string
      required:
      - limit
      - page
      type: object
    GeneralArrayResponse:
      description: General response object
      example:
        code: 0
        data:
        - createdAt: 2023-10-01T12:00:00Z
          deletedAt: 2023-10-01T12:00:00Z
          updatedBy: admin
          createdBy: admin
          name: admin
          description: Administrator role with full access
          deletedBy: admin
          status: active
          updatedAt: 2023-10-01T12:00:00Z
        - createdAt: 2023-10-01T12:00:00Z
          deletedAt: 2023-10-01T12:00:00Z
          updatedBy: admin
          createdBy: admin
          name: admin
          description: Administrator role with full access
          deletedBy: admin
          status: active
          updatedAt: 2023-10-01T12:00:00Z
        message: message
      properties:
        code:
          description: Response code
          type: integer
        message:
          description: Response message
          type: string
        data:
          items:
            $ref: '#/components/schemas/BaseRole'
          type: array
      type: object
    BaseRole:
      description: Base role object with common properties
      example:
        createdAt: 2023-10-01T12:00:00Z
        deletedAt: 2023-10-01T12:00:00Z
        updatedBy: admin
        createdBy: admin
        name: admin
        description: Administrator role with full access
        deletedBy: admin
        status: active
        updatedAt: 2023-10-01T12:00:00Z
      properties:
        name:
          example: admin
          type: string
        description:
          example: Administrator role with full access
          type: string
        status:
          enum:
          - active
          - inactive
          - pending
          - canceled
          - deleted
          example: active
          type: string
        createdAt:
          example: 2023-10-01T12:00:00Z
          format: date-time
          type: string
        updatedAt:
          example: 2023-10-01T12:00:00Z
          format: date-time
          type: string
        createdBy:
          example: admin
          type: string
        updatedBy:
          example: admin
          type: string
        deletedAt:
          example: 2023-10-01T12:00:00Z
          format: date-time
          type: string
        deletedBy:
          example: admin
          type: string
      required:
      - description
      - name
      type: object
